# Generated by Django 3.1.7 on 2021-04-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujoapp', '0005_auto_20210411_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='bio', max_length=100),
            preserve_default=False,
        ),
    ]
