# Generated by Django 3.1.7 on 2021-04-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujoapp', '0006_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.CharField(default='https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='A short description about yourself', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Your Nickname', max_length=100),
        ),
    ]
