# Generated by Django 3.1.7 on 2021-04-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bujoapp', '0007_auto_20210411_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/a/a0/Pierre-Person.jpg', max_length=1000),
        ),
    ]
